name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: print
      run: |
        echo $HOME
        echo $GITHUB_WORKSPACE
        pwd

    - name: Install gomod-gen
      run: |
        go get github.com/appscodelabs/gomod-gen
        curl -sL https://github.com/appscodelabs/gomod-gen/raw/master/kubernetes/v1.18.3/go.mod.json > /tmp/go.mod.json

    - name: Prepare git
      run: |
        git config --global user.name "1gtm"
        git config --global user.email "1gtm@appscode.com"

    - name: Install hub
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        sudo mv bin/hub /usr/local/bin

    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
      run: |
        git clone https://1gtm:${GITHUB_TOKEN}@github.com/stashed/apimachinery.git repo
        cd repo
        export PR_BRANCH=k8s-gomod-refresher-$(date +%s)
        echo $PR_BRANCH
        git checkout -b $PR_BRANCH
        gomod-gen --gomod-json-file=/tmp/go.mod.json
        go mod tidy
        go mod vendor
        git add --all
        git commit -a -s -m "Update to Kubernetes v1.18.3"
        git push origin $PR_BRANCH -f
        $GITHUB_WORKSPACE/bin/hub pull-request -m "Update to Kubernetes v1.18.3"
