name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        curl -fsSL -O https://github.com/cli/cli/releases/download/v0.9.0/gh_0.9.0_linux_amd64.deb
        sudo apt install ./gh_*_linux_amd64.deb
        rm ./gh_*_linux_amd64.deb

    - name: Install gomod-gen
      run: |
        curl -fsSL -O https://github.com/appscodelabs/gomod-gen/releases/download/v0.1.1/gomod-gen-linux-amd64
        chmod +x gomod-gen-linux-amd64
        sudo mv gomod-gen-linux-amd64 /usr/local/bin/gomod-gen

    - name: Prepare git
      run: |
        git config --global user.name "1gtm"
        git config --global user.email "1gtm@appscode.com"

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        sudo mv bin/hub /usr/local/bin

    - name: Update desired go.mod
      run: |
        ./v1.18.3/update.sh

    - name: Refresh repositories
      env:
        GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
      run: |
        ./refresh-repo.sh repos.txt
